fix build error when option UMR_NO_DRM=1
when option of UMR_NO_DRM is enabled, it will cause umr build fails.

error log:
/usr/bin/ld: libumrapp.a(vbios.c.o): in function `umr_print_vbios_info':
/home/kevin/Work/gitroot/umr/src/app/vbios.c:40: undefined reference to
`umr_query_drm_vbios'
collect2: error: ld returned 1 exit status

Signed-off-by: Wang Yang <kevinyang.wang@amd.com>
Reviewed-by: Tom St Denis <tom.stdenis@amd.com>